sudo: required

services:
  - docker

before_install:
  - docker build -t enjakarthikkumar/docker-react -f Dockerfile.dev .

script:
  - docker run enjakarthikkumar/docker-react npm run test -- --coverage
